/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MenusRouteImport } from './routes/menus'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LocationsSlugRouteImport } from './routes/locations.$slug'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPopupsRouteImport } from './routes/admin.popups'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminMenusRouteImport } from './routes/admin.menus'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLocationsRouteImport } from './routes/admin.locations'
import { Route as AdminLinksRouteImport } from './routes/admin.links'
import { Route as AdminLaunchRouteImport } from './routes/admin.launch'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminFilesRouteImport } from './routes/admin.files'
import { Route as AdminAboutRouteImport } from './routes/admin.about'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MenusRoute = MenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/locations/$slug',
  path: '/locations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPopupsRoute = AdminPopupsRouteImport.update({
  id: '/admin/popups',
  path: '/admin/popups',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMenusRoute = AdminMenusRouteImport.update({
  id: '/admin/menus',
  path: '/admin/menus',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/admin/locations',
  path: '/admin/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLinksRoute = AdminLinksRouteImport.update({
  id: '/admin/links',
  path: '/admin/links',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLaunchRoute = AdminLaunchRouteImport.update({
  id: '/admin/launch',
  path: '/admin/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/admin/gallery',
  path: '/admin/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFilesRoute = AdminFilesRouteImport.update({
  id: '/admin/files',
  path: '/admin/files',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAboutRoute = AdminAboutRouteImport.update({
  id: '/admin/about',
  path: '/admin/about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/menus': typeof MenusRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/files': typeof AdminFilesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/launch': typeof AdminLaunchRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menus': typeof AdminMenusRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/popups': typeof AdminPopupsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/locations/': typeof LocationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/menus': typeof MenusRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/files': typeof AdminFilesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/launch': typeof AdminLaunchRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menus': typeof AdminMenusRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/popups': typeof AdminPopupsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/locations': typeof LocationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/menus': typeof MenusRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/files': typeof AdminFilesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/launch': typeof AdminLaunchRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menus': typeof AdminMenusRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/popups': typeof AdminPopupsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/locations/': typeof LocationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/menus'
    | '/sitemap.xml'
    | '/admin/about'
    | '/admin/files'
    | '/admin/gallery'
    | '/admin/launch'
    | '/admin/links'
    | '/admin/locations'
    | '/admin/login'
    | '/admin/menus'
    | '/admin/messages'
    | '/admin/popups'
    | '/admin/settings'
    | '/locations/$slug'
    | '/admin/'
    | '/locations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/menus'
    | '/sitemap.xml'
    | '/admin/about'
    | '/admin/files'
    | '/admin/gallery'
    | '/admin/launch'
    | '/admin/links'
    | '/admin/locations'
    | '/admin/login'
    | '/admin/menus'
    | '/admin/messages'
    | '/admin/popups'
    | '/admin/settings'
    | '/locations/$slug'
    | '/admin'
    | '/locations'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/menus'
    | '/sitemap.xml'
    | '/admin/about'
    | '/admin/files'
    | '/admin/gallery'
    | '/admin/launch'
    | '/admin/links'
    | '/admin/locations'
    | '/admin/login'
    | '/admin/menus'
    | '/admin/messages'
    | '/admin/popups'
    | '/admin/settings'
    | '/locations/$slug'
    | '/admin/'
    | '/locations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  MenusRoute: typeof MenusRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminAboutRoute: typeof AdminAboutRoute
  AdminFilesRoute: typeof AdminFilesRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminLaunchRoute: typeof AdminLaunchRoute
  AdminLinksRoute: typeof AdminLinksRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMenusRoute: typeof AdminMenusRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminPopupsRoute: typeof AdminPopupsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  LocationsSlugRoute: typeof LocationsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menus': {
      id: '/menus'
      path: '/menus'
      fullPath: '/menus'
      preLoaderRoute: typeof MenusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/locations/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/popups': {
      id: '/admin/popups'
      path: '/admin/popups'
      fullPath: '/admin/popups'
      preLoaderRoute: typeof AdminPopupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/menus': {
      id: '/admin/menus'
      path: '/admin/menus'
      fullPath: '/admin/menus'
      preLoaderRoute: typeof AdminMenusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/admin/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/links': {
      id: '/admin/links'
      path: '/admin/links'
      fullPath: '/admin/links'
      preLoaderRoute: typeof AdminLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/launch': {
      id: '/admin/launch'
      path: '/admin/launch'
      fullPath: '/admin/launch'
      preLoaderRoute: typeof AdminLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/admin/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/files': {
      id: '/admin/files'
      path: '/admin/files'
      fullPath: '/admin/files'
      preLoaderRoute: typeof AdminFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/about': {
      id: '/admin/about'
      path: '/admin/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AdminAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  MenusRoute: MenusRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminAboutRoute: AdminAboutRoute,
  AdminFilesRoute: AdminFilesRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminLaunchRoute: AdminLaunchRoute,
  AdminLinksRoute: AdminLinksRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMenusRoute: AdminMenusRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminPopupsRoute: AdminPopupsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  LocationsSlugRoute: LocationsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
